# Generated by Django 4.2.13 on 2024-07-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twitter", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="twitterpost",
            name="comments_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="twitterpost",
            name="like_counts",
            field=models.IntegerField(default=0),
        ),
    ]
