# Generated by Django 4.2.13 on 2024-06-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetails",
            name="password",
            field=models.CharField(max_length=200),
        ),
    ]
