# Generated by Django 4.2.13 on 2024-07-15 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetails",
            name="users",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="app_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
