# Generated by Django 4.2.13 on 2024-07-18 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0002_comment_like_counts_alter_comment_user_and_more"),
        ("app_users", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetails",
            name="videos_history",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_video_history",
                to="video.videodetails",
            ),
        ),
    ]
