# Generated by Django 4.2.13 on 2024-07-18 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0002_initial"),
        ("video", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="like_counts",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commented_by_user",
                to="app_users.userdetails",
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="liked_by_user",
                to="app_users.userdetails",
            ),
        ),
    ]
