# Generated by Django 4.2.13 on 2024-07-04 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="comment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="like_comments",
                to="video.comment",
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="video",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="like_video",
                to="video.videodetails",
            ),
        ),
        migrations.AlterField(
            model_name="videodetails",
            name="video_title",
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
