# Generated by Django 4.2.13 on 2024-07-24 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("twitter", "0002_twitterpost_comments_count_twitterpost_like_counts"),
        ("video", "0002_comment_like_counts_alter_comment_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="like",
            name="twitter",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="like_twittwer_post",
                to="twitter.twitterpost",
            ),
        ),
    ]
